name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: ^3.2.1

dependencies:
  ngdart: ^8.0.0-dev.4
  ngrouter: ^4.0.0-dev.3
  ngforms: ^5.0.0-dev.3

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  ngtest: ^5.0.0-dev.3
  # #docregion build-dependencies
  build_runner: ^2.2.0
  build_test: ^2.1.5
  build_web_compilers: ^4.0.0
  # #enddocregion build-dependencies
  test: ^1.24.0
# #enddocregion dev_dependencies